import { Metadata } from "next";
import { Figtree } from "next/font/google";
import { PropsWithChildren } from "react";
import "@repo/tailwind-config/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const figtree = Figtree({
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={figtree.className}>
      <body className="bg-base-0">{children}</body>
    </html>
  );
}
